### ISSUE TITLE
Code execution not firing.

### ISSUE THREAD

**Issue by TomExMachina** [jaemil/agentsflow#1]
It's supposed to run any code found within any message but it's not. It's possibly related to the way I hijacked the messaging. What I didn't doesn't rly seem hacky though it might be. Initialization of agents was moved to https://github.com/jaemil/autogen_websocket/blob/main/autogen_client/initialize.py

The autogen file conversable_agent.py is probably where the trouble is happening

https://github.com/microsoft/autogen/blob/main/autogen/agentchat/conversable_agent.py

It could have something to do with the agent naming and/or my one class override since `sender` is a thing used to determine code execution permission. The permission configs we have set seem to be correct: https://github.com/jaemil/autogen_websocket/blob/7bdb509d403c004b9c5579732a8cf25f5c1b672f/autogen_client/initialize.py#L24

**Comment by Nivek92** [comment]
The issue seems to be that by default, the functions are checked in order:
1. check_termination_and_human_reply
2. generate_function_call_reply
3. generate_code_execution_reply
4. generate_oai_reply

and because we always ask the user for a reply, it always exits with check_termination_and_human_reply

**Comment by TomExMachina** [comment]
> The issue seems to be that by default, the functions are checked in order:
> 
> 1. check_termination_and_human_reply
> 2. generate_function_call_reply
> 3. generate_code_execution_reply
> 4. generate_oai_reply
> 
> and because we always ask the user for a reply, it always exits with check_termination_and_human_reply
> 
> File: https://github.com/microsoft/autogen/blob/main/autogen/agentchat/conversable_agent.py Method: generate_reply (line 733)

Will have to check it out. Also saw this https://github.com/microsoft/autogen/blob/09c9dbe944e9a353e6666df96ebb5e2ae79f6817/autogen/agentchat/conversable_agent.py#L94

also of note is that I may be able to replace my current method of capturing messages with some implementation of https://microsoft.github.io/autogen/docs/reference/agentchat/conversable_agent#register_reply though your findings suggest that modifying message capture may not be necessary.

I'll be able to do a thorough review of everything after sleep. Feel free to crack on at will.

**Comment by TomExMachina** [comment]
Was fixed in: https://github.com/jaemil/agentsflow/commit/d798b4409bf0e1adfe57039df10f68bb3604259e
